name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    #　手動トリガー用
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # ステップ１：リポジトリのコードを取得
      - uses: actions/checkout@v6
      # ステップ２：pnpmのセットアップと依存関係のインストール
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      # ステップ３：Node.jsのセットアップ
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "pnpm"
      # ステップ４：依存関係のインストール
      - name: Install dependencies
        run: pnpm install
      # ステップ５：Playwrightブラウザのインストール
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      # ステップ６：プロジェクトのビルド
      - name: build project
        run: pnpm run build
      # ステップ７：Playwrightテストの実行
      - name: Run Playwright tests
        run: pnpm exec playwright test
      # ステップ８：Playwrightレポートのアップロード
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
